name: Feature request
description: Suggest a tweak/fix/feature to add to the game
title: "[Feature Request]: "
labels: feature
body:
  - id: disclaimer
    type: markdown
    attributes:
      value: |
        Please feel free to suggest any tweak/fix/feature you'd like to see added to the game!
        
        We'd appreciate it if you could [search through the existing issues](https://github.com/emoose/OutRun2006Tweaks/issues) to see if something similar has already been suggested first.
        (replying to existing issues would also help us know which ones should be prioritized)
  - id: feature
    type: textarea
    attributes:
      label: Describe the feature you'd like to see added
    validations:
      required: true