from pathlib import Path
p=Path('src/hooks_wheel_ffb.cpp'); s=p.read_text()

def r(a,b,n):
    global s
    c=s.count(a)
    if c!=1: raise SystemExit(f'{n}: {c}')
    s=s.replace(a,b,1); print('patched',n)

r('#include <cstring>\n#include <string>\n','#include <cstring>\n#include <cstdio>\n#include <string>\n','cstdio')
r('''    Setting<std::string> WheelFFBDeviceName{\n        "WheelFFB", "DeviceName", "MOZA",\n        "Case-insensitive substring used to select the FFB wheel. Empty selects the first non-virtual FFB device."\n    };\n''','''    Setting<std::string> WheelFFBDeviceName{\n        "WheelFFB", "DeviceName", "MOZA",\n        "Case-insensitive substring used to select the FFB wheel. Empty selects the first non-virtual FFB device."\n    };\n\n    Setting<std::string> WheelFFBDeviceGuid{\n        "WheelFFB", "DeviceGuid", "",\n        "Exact DirectInput instance GUID selected by F11 Wheel Setup; DeviceName remains the fallback."\n    };\n''','setting')
r('''    bool is_virtual_device_name(const std::string& lowered)\n''','''    std::string directinput_guid_key(const GUID& guid)\n    {\n        char b[64]{};\n        std::snprintf(b, sizeof(b),\n            "%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X",\n            (unsigned)guid.Data1, (unsigned)guid.Data2, (unsigned)guid.Data3,\n            (unsigned)guid.Data4[0], (unsigned)guid.Data4[1],\n            (unsigned)guid.Data4[2], (unsigned)guid.Data4[3],\n            (unsigned)guid.Data4[4], (unsigned)guid.Data4[5],\n            (unsigned)guid.Data4[6], (unsigned)guid.Data4[7]);\n        return lower_copy(b);\n    }\n\n    bool is_virtual_device_name(const std::string& lowered)\n''','helper')
r('''            bool found = false;\n            bool ignoreName = false;\n''','''            bool found = false;\n            bool ignoreName = false;\n            bool matchGuidOnly = false;\n''','ctx')
r('''            const std::string wanted =\n                lower_copy(Settings::WheelFFBDeviceName.get().c_str());\n''','''            const std::string wanted =\n                lower_copy(Settings::WheelFFBDeviceName.get().c_str());\n            const std::string wantedGuid =\n                lower_copy(Settings::WheelFFBDeviceGuid.get().c_str());\n''','callback config')
r('''            if (!ctx->ignoreName && !wanted.empty() &&\n                instanceName.find(wanted) == std::string::npos &&\n                productName.find(wanted) == std::string::npos)\n''','''            if (ctx->matchGuidOnly &&\n                (wantedGuid.empty() || directinput_guid_key(instance->guidInstance) != wantedGuid))\n                return DIENUM_CONTINUE;\n\n            if (!ctx->matchGuidOnly && !ctx->ignoreName && !wanted.empty() &&\n                instanceName.find(wanted) == std::string::npos &&\n                productName.find(wanted) == std::string::npos)\n''','callback match')
r('''            EnumContext ctx{};\n            ctx.self = this;\n\n            hr = directInput_->EnumDevices(\n                DI8DEVCLASS_GAMECTRL,\n                enum_devices_callback,\n                &ctx,\n                DIEDFL_ATTACHEDONLY | DIEDFL_FORCEFEEDBACK);\n''','''            EnumContext ctx{};\n            ctx.self = this;\n            const std::string configuredGuid =\n                lower_copy(Settings::WheelFFBDeviceGuid.get().c_str());\n\n            if (!configuredGuid.empty())\n            {\n                ctx.matchGuidOnly = true;\n                hr = directInput_->EnumDevices(\n                    DI8DEVCLASS_GAMECTRL, enum_devices_callback, &ctx,\n                    DIEDFL_ATTACHEDONLY | DIEDFL_FORCEFEEDBACK);\n                if (FAILED(hr))\n                {\n                    release_directinput();\n                    return false;\n                }\n                if (!ctx.found)\n                {\n                    spdlog::warn(\n                        "WheelFFB: saved DirectInput GUID '{}' not attached; falling back to DeviceName",\n                        Settings::WheelFFBDeviceGuid.get());\n                    ctx = {};\n                    ctx.self = this;\n                }\n            }\n\n            if (!ctx.found)\n            {\n                hr = directInput_->EnumDevices(\n                    DI8DEVCLASS_GAMECTRL, enum_devices_callback, &ctx,\n                    DIEDFL_ATTACHEDONLY | DIEDFL_FORCEFEEDBACK);\n            }\n''','guid-first enumerate')
r('''            selectedGuid_ = ctx.selectedGuid;\n            selectedName_ = ctx.selectedName;\n''','''            selectedGuid_ = ctx.selectedGuid;\n            selectedName_ = ctx.selectedName;\n            selectedConfiguredGuid_ = lower_copy(Settings::WheelFFBDeviceGuid.get().c_str());\n            selectedConfiguredName_ = lower_copy(Settings::WheelFFBDeviceName.get().c_str());\n            spdlog::info("WheelFFB: selected DirectInput identity '{}' / '{}'",\n                selectedName_, directinput_guid_key(selectedGuid_));\n''','selected identity cache')
r('''            if (deviceReinitPending_)\n            {\n''','''            if (initialized_)\n            {\n                const std::string guidNow = lower_copy(Settings::WheelFFBDeviceGuid.get().c_str());\n                const std::string nameNow = lower_copy(Settings::WheelFFBDeviceName.get().c_str());\n                if (guidNow != selectedConfiguredGuid_ || nameNow != selectedConfiguredName_)\n                {\n                    selectedConfiguredGuid_ = guidNow;\n                    selectedConfiguredName_ = nameNow;\n                    request_device_reinitialize("configured wheel identity changed", S_OK);\n                    return;\n                }\n            }\n\n            if (deviceReinitPending_)\n            {\n''','live identity reinit')
r('''        std::string selectedName_;\n        HWND gameHwnd_ = nullptr;\n''','''        std::string selectedName_;\n        std::string selectedConfiguredGuid_;\n        std::string selectedConfiguredName_;\n        HWND gameHwnd_ = nullptr;\n''','identity state')
p.write_text(s)
print('Applied exact GUID-first FFB device selection and live identity reinit')
