from pathlib import Path
p=Path('src/overlay/wheel_setup_ui.cpp'); s=p.read_text()

def r(a,b,n):
    global s
    c=s.count(a)
    if c!=1: raise SystemExit(f'{n}: {c}')
    s=s.replace(a,b,1); print('patched',n)

r('''    extern Setting<std::string> WheelFFBDeviceName;\n''','''    extern Setting<std::string> WheelFFBDeviceName;\n    extern Setting<std::string> WheelFFBDeviceGuid;\n''','extern')
r('''    Setting<std::string> WheelUniversalDeviceName{\n        "Controls", "WheelUniversalDeviceName", "",\n        "DirectInput product name selected by F11 Wheel Setup."\n    };\n''','''    Setting<std::string> WheelUniversalDeviceName{\n        "Controls", "WheelUniversalDeviceName", "",\n        "DirectInput product name selected by F11 Wheel Setup."\n    };\n\n    Setting<std::string> WheelUniversalDeviceGuid{\n        "Controls", "WheelUniversalDeviceGuid", "",\n        "Exact DirectInput instance GUID selected by F11 Wheel Setup."\n    };\n''','setting')
r('''    bool is_virtual_name(const std::string& name)\n''','''    std::string lower_identity(std::string value)\n    {\n        std::transform(value.begin(), value.end(), value.begin(),\n            [](unsigned char c) { return static_cast<char>(std::tolower(c)); });\n        return value;\n    }\n\n    std::string wheel_guid_key(const GUID& guid)\n    {\n        char b[64]{};\n        std::snprintf(b, sizeof(b),\n            "%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X",\n            (unsigned)guid.Data1, (unsigned)guid.Data2, (unsigned)guid.Data3,\n            (unsigned)guid.Data4[0], (unsigned)guid.Data4[1],\n            (unsigned)guid.Data4[2], (unsigned)guid.Data4[3],\n            (unsigned)guid.Data4[4], (unsigned)guid.Data4[5],\n            (unsigned)guid.Data4[6], (unsigned)guid.Data4[7]);\n        return lower_identity(b);\n    }\n\n    bool is_virtual_name(const std::string& name)\n''','helpers')
r('''        GUID guid{};\n        std::string name;\n''','''        GUID guid{};\n        std::string guidKey;\n        std::string name;\n''','device key')
r('''        bool select_by_name(const std::string& wanted)\n        {\n            if (wanted == selectedName_ && device_)\n                return true;\n\n            release_device();\n            if (devices_.empty())\n                enumerate();\n\n            int index = -1;\n            for (size_t i = 0; i < devices_.size(); ++i)\n            {\n                if (devices_[i].name == wanted)\n                {\n                    index = int(i);\n                    break;\n                }\n            }\n            if (index < 0 && wanted.empty() && !devices_.empty())\n                index = 0;\n            if (index < 0)\n                return false;\n            return open(index);\n        }\n''','''        bool select_by_identity(const std::string& wantedGuid, const std::string& wantedName)\n        {\n            const std::string guid = lower_identity(wantedGuid);\n            if (device_ && !guid.empty() && guid == selectedGuidKey_) return true;\n            if (device_ && guid.empty() && wantedName == selectedName_) return true;\n\n            release_device();\n            if (devices_.empty()) enumerate();\n            int index = -1;\n            if (!guid.empty())\n                for (size_t i=0; i<devices_.size(); ++i)\n                    if (devices_[i].guidKey == guid) { index=int(i); break; }\n            if (index < 0 && !wantedName.empty())\n                for (size_t i=0; i<devices_.size(); ++i)\n                    if (devices_[i].name == wantedName) { index=int(i); break; }\n            if (index < 0 && guid.empty() && wantedName.empty() && !devices_.empty()) index=0;\n            return index >= 0 ? open(index) : false;\n        }\n''','identity select')
r('''                if (!select_by_name(Settings::WheelUniversalDeviceName.get()))\n                    return false;\n''','''                if (!select_by_identity(\n                        Settings::WheelUniversalDeviceGuid.get(),\n                        Settings::WheelUniversalDeviceName.get()))\n                    return false;\n''','poll identity')
r('''            selectedName_.clear();\n            state_ = {};\n''','''            selectedName_.clear();\n            selectedGuidKey_.clear();\n            state_ = {};\n''','clear key')
r('''            DeviceInfo info{};\n            info.guid = instance->guidInstance;\n            info.name = product;\n''','''            DeviceInfo info{};\n            info.guid = instance->guidInstance;\n            info.guidKey = wheel_guid_key(info.guid);\n            info.name = product;\n''','enum key')
r('''            device_ = device;\n            selectedName_ = devices_[index].name;\n            return true;\n''','''            device_ = device;\n            selectedName_ = devices_[index].name;\n            selectedGuidKey_ = devices_[index].guidKey;\n            return true;\n''','open key')
r('''        std::vector<DeviceInfo> devices_;\n        std::string selectedName_;\n        DIJOYSTATE2 state_{};\n''','''        std::vector<DeviceInfo> devices_;\n        std::string selectedName_;\n        std::string selectedGuidKey_;\n        DIJOYSTATE2 state_{};\n''','state')
r('''            Settings::WheelUniversalDeviceName = info.name;\n            Settings::WheelFFBDeviceName = info.name;\n            gReader.select_by_name(info.name);\n''','''            Settings::WheelUniversalDeviceName = info.name;\n            Settings::WheelUniversalDeviceGuid = info.guidKey;\n            Settings::WheelFFBDeviceName = info.name;\n            Settings::WheelFFBDeviceGuid = info.guidKey;\n            gReader.select_by_identity(info.guidKey, info.name);\n''','select store')
r('''            if (ImGui::BeginCombo("Wheel", preview.c_str()))\n            {\n                for (size_t i = 0; i < devices.size(); ++i)\n                {\n                    const bool selected = devices[i].name == Settings::WheelUniversalDeviceName.get();\n                    if (ImGui::Selectable(devices[i].name.c_str(), selected))\n                        select_device(devices[i]);\n                    if (selected) ImGui::SetItemDefaultFocus();\n                }\n                ImGui::EndCombo();\n            }\n\n            if (!devices.empty())\n            {\n                for (const auto& dev : devices)\n                    if (dev.name == Settings::WheelUniversalDeviceName.get())\n                        ImGui::TextDisabled("%lu axes / %lu buttons / %lu POV / FFB %s",\n                            dev.axes, dev.buttons, dev.povs, dev.ffb ? "yes" : "no");\n            }\n''','''            const std::string configuredGuid =\n                lower_identity(Settings::WheelUniversalDeviceGuid.get());\n            auto isSelectedDevice = [&](const DeviceInfo& dev)\n            {\n                return !configuredGuid.empty()\n                    ? dev.guidKey == configuredGuid\n                    : dev.name == Settings::WheelUniversalDeviceName.get();\n            };\n            if (ImGui::BeginCombo("Wheel", preview.c_str()))\n            {\n                for (size_t i = 0; i < devices.size(); ++i)\n                {\n                    const bool selected = isSelectedDevice(devices[i]);\n                    const std::string label = devices[i].name + "##" + devices[i].guidKey;\n                    if (ImGui::Selectable(label.c_str(), selected)) select_device(devices[i]);\n                    if (selected) ImGui::SetItemDefaultFocus();\n                }\n                ImGui::EndCombo();\n            }\n            for (const auto& dev : devices)\n                if (isSelectedDevice(dev))\n                    ImGui::TextDisabled("%lu axes / %lu buttons / %lu POV / FFB %s / GUID %s",\n                        dev.axes, dev.buttons, dev.povs, dev.ffb ? "yes" : "no", dev.guidKey.c_str());\n''','combo')
p.write_text(s)
print('Applied exact DirectInput GUID identity to F11 wheel setup')
