on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [ Win32 ]
        build_type: [ Release ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A ${{matrix.arch}} ..
          
      - name: Add older VC2022 redist workaround to safetyhook
        shell: pwsh
        run: |
          (Get-Content build/_deps/safetyhook-build/safetyhook.vcxproj) -replace 'ZYCORE_STATIC_BUILD', '_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR;ZYCORE_STATIC_BUILD' | Set-Content build/_deps/safetyhook-build/safetyhook.vcxproj
          (Get-Content build/_deps/zydis-build/Zydis.vcxproj) -replace 'ZYCORE_STATIC_BUILD', '_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR;ZYCORE_STATIC_BUILD' | Set-Content build/_deps/zydis-build/Zydis.vcxproj
          (Get-Content build/_deps/zydis-build/zycore/Zycore.vcxproj) -replace 'ZYCORE_STATIC_BUILD', '_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR;ZYCORE_STATIC_BUILD' | Set-Content build/_deps/zydis-build/zycore/Zycore.vcxproj
          
      - name: Build
        run: |
          cmake --build build --config ${{matrix.build_type}}
          
      - name: Copy settings
        shell: pwsh
        run: |
          cp OutRun2006Tweaks.ini build/bin/OutRun2006Tweaks.ini
          
      - name: Download OR2006C2C
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/emoose/OutRun2006Tweaks/releases/download/v0.1/OR2006C2C.EXE -OutFile build/bin/OR2006C2C.exe
          
      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
          name: outrun2006tweaks-${{ github.sha }}
          path: build/bin/
